### PR TITLE
Added getMilliseconds() and updateLastClickTime() functions

### PR DESCRIPTION
**Pull request by vanodevium**

### CODE REVIEW

**Comment by webdevium** [comment]
@BPower0036 
It seems to me, yes. After all, if we have a function, then at any moment we can replace this behavior, say, for seconds. As a plus, this code is easy to test: we just mock this function.

**Comment by webdevium** [comment]
In your new code, string `lastInteractionTime = new Date().getTime();` is repeated six times.
Purely aesthetically, it is better to replace with a function for testing purposes. Imho DRY principle.

As for the `getTimestamp()`, you do not need to replace it. It is needed only for logging. LGTM.

**Comment by JohnyP36** [comment]
@webdevium But the string `lastInteractionTime = new Date().getTime();` seems me is also for logging. Isn't it?

**Comment by BPower0036** [comment]
@JohnyP36 No. It is for knowing when the extension last interacted.

**Pull request closed without merging**
